site_name: Mein Rezept- & Restaurant-Blog
theme:
  name: material
  language: de             # UI-Sprache für die Default-Variante
  features:
    - navigation.sections
    - navigation.instant
    - content.tabs.link
    - content.code.annotate
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: [de, en]
  - i18n:
      default_language: de
      languages:
        - de
        - en
      docs_structure: suffix
      nav_translations:
        de:
          Start: Start
          Rezepte: Rezepte
          Restaurant-Guides: Restaurant-Guides
          Übersicht: Übersicht
        en:
          Start: Home
          Rezepte: Recipes
          Restaurant-Guides: Restaurant Guides
          Übersicht: Overview
