site_name: Mein Rezept- & Restaurant-Blog
theme:
  name: material
  language: de

plugins:
  - search:
      lang: [de, en]
  - i18n:
      default_language: de
      docs_structure: suffix
      languages:
        - locale: de
          name: Deutsch
          default: true
        - locale: en
          name: English
      nav_translations:
        de:
          Start: Start
          Rezepte: Rezepte
          Restaurant-Guides: Restaurant-Guides
          Übersicht: Übersicht
        en:
          Start: Home
          Rezepte: Recipes
          Restaurant-Guides: Restaurant Guides
          Übersicht: Overview
